### ISSUE TITLE
PID settings should go in their own yaml

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/1721-RapidReact#53]
This is low priority but simple enough

**Comment by RishiKumarRay** [comment]
can you elaboarte this ?

**Comment by KenwoodFox** [comment]
> can you elaboarte this ?

Yep! The pid settings should be in their own yaml instead of in `hardware.yaml`, fixing this will involve using the yaml loader to load the seperate settings file when adjusting PID

The main reason for this, is that the hardware config is useful for in-the-pits work, but the pid is not.

Start under `rio/constants` and break the pid sections away, should look something like this:

robot_hardware.yaml
```yaml
subsytem:
	motor_id: 2
	another_motor_id: 69
```

robot_pid.yaml
```yaml
subsystem:
	motor_kp: 0
	motor_kd: 0
	motor_ki: 69
```

etc.

And to load them, you'll need another load command in python:
```python
constants = getConstants("robot_hardware")
pidConstants = getConstants("robot_pid")
```
